# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
# Comment by Guanao Yan 20221030
# Note the indent should be consistent like
# main:
#  - name: Home
#    url: '#about'
#    weight: 10
# Use content/home/ + active: false to add/remove Widgets

main:
  - name: Home
    url: '#about'
    weight: 10
  # - name: Posts
  #   url: '#posts'
  #   weight: 20
  # - name: Projects
  #   url: '#projects'
  #   weight: 30
  - name: Publications
    url: '#publications'
    weight: 40
  - name: Talks
    url: '#talks'
    weight: 50
  # - name: Contact
  #   url: '#contact'
  #   weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
